-- ==============================================================================
-- CapVeri.com - Sections 6-23 for Manual Testing Seed Data
-- ==============================================================================
-- This file contains ONLY sections 6-23 to be appended to sections 1-5
-- Run this after truncating the incomplete version

-- ==============================================================================
-- SECTION 6: LEASES (48 Total)
-- ==============================================================================

DO $$
BEGIN
    RAISE NOTICE '[6/23] Creating 48 leases with varied recovery profiles...';
END $$;

-- Downtown Tower Leases (15 total) - Acme Property Management
-- Cumulative caps (5), Non-cumulative caps (5), Cumulative compounding (3), No caps (2)

INSERT INTO leases (id, property_id, unit_id, tenant_name, start_date, end_date, status, recovery_profile, created_at, updated_at)
VALUES
    -- Cumulative caps (leases 001-005)
    ('dddddddd-dddd-dddd-dddd-ddddddddd001'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0201' LIMIT 1),
     'TechCorp Inc',
     '2023-01-01'::date,
     '2028-12-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.05", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '2 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd002'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0301' LIMIT 1),
     'FinanceGroup LLC',
     '2022-06-01'::date,
     '2027-05-31'::date,
     'active',
     '{"base_year": 2022, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.048", "cap_type": "cumulative", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '2.5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd003'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0401' LIMIT 1),
     'Legal Associates',
     '2023-03-01'::date,
     '2028-02-28'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.042", "cap_type": "cumulative", "cap_rate": "0.06", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '21 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd004'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0501' LIMIT 1),
     'Marketing Pro Agency',
     '2023-07-01'::date,
     '2028-06-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.038", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '18 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd005'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0601' LIMIT 1),
     'Consulting Partners',
     '2024-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2024, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.045", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '12 months',
     NOW()),

    -- Non-cumulative caps (leases 006-010)
    ('dddddddd-dddd-dddd-dddd-ddddddddd006'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0701' LIMIT 1),
     'Architecture Studio',
     '2023-02-01'::date,
     '2028-01-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.040", "cap_type": "non_cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '22 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd007'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0801' LIMIT 1),
     'Engineering Firm',
     '2023-04-01'::date,
     '2028-03-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.052", "cap_type": "non_cumulative", "cap_rate": "0.06", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '20 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd008'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '0901' LIMIT 1),
     'Healthcare Advisors',
     '2023-06-01'::date,
     '2028-05-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.047", "cap_type": "non_cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '18 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd009'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '1001' LIMIT 1),
     'Real Estate Services',
     '2023-09-01'::date,
     '2028-08-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.043", "cap_type": "non_cumulative", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '15 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd010'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '1101' LIMIT 1),
     'Insurance Brokers',
     '2024-02-01'::date,
     '2029-01-31'::date,
     'active',
     '{"base_year": 2024, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.046", "cap_type": "non_cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '11 months',
     NOW()),

    -- Cumulative compounding caps (leases 011-013)
    ('dddddddd-dddd-dddd-dddd-ddddddddd011'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '1201' LIMIT 1),
     'Software Development Co',
     '2022-01-01'::date,
     '2027-12-31'::date,
     'active',
     '{"base_year": 2022, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.055", "cap_type": "cumulative_compounding", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '3 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd012'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '1301' LIMIT 1),
     'Media Production LLC',
     '2023-05-01'::date,
     '2028-04-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.041", "cap_type": "cumulative_compounding", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '19 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd013'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '1401' LIMIT 1),
     'Investment Advisors',
     '2023-10-01'::date,
     '2028-09-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.039", "cap_type": "cumulative_compounding", "cap_rate": "0.06", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '14 months',
     NOW()),

    -- No caps (leases 014-015)
    ('dddddddd-dddd-dddd-dddd-ddddddddd014'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '1501' LIMIT 1),
     'Accounting Services',
     '2023-08-01'::date,
     '2028-07-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.044", "cap_type": "none", "cap_rate": null, "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '16 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd015'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc001'::uuid AND unit_number = '1601' LIMIT 1),
     'Design Studio',
     '2024-03-01'::date,
     '2029-02-28'::date,
     'active',
     '{"base_year": 2024, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.037", "cap_type": "none", "cap_rate": null, "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '10 months',
     NOW())
ON CONFLICT (id) DO NOTHING;

-- Suburban Office Park Leases (10 total) - Acme Property Management
INSERT INTO leases (id, property_id, unit_id, tenant_name, start_date, end_date, status, recovery_profile, created_at, updated_at)
VALUES
    ('dddddddd-dddd-dddd-dddd-ddddddddd016'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 101' LIMIT 1),
     'BioTech Research Inc',
     '2023-01-01'::date,
     '2028-12-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.062", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '2 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd017'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 102' LIMIT 1),
     'Data Analytics Corp',
     '2023-02-01'::date,
     '2028-01-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.058", "cap_type": "non_cumulative", "cap_rate": "0.06", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '22 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd018'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 103' LIMIT 1),
     'Cloud Solutions LLC',
     '2023-03-01'::date,
     '2028-02-28'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.055", "cap_type": "cumulative", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '21 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd019'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 104' LIMIT 1),
     'Cybersecurity Firm',
     '2023-04-01'::date,
     '2028-03-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.051", "cap_type": "cumulative_compounding", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '20 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd020'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 105' LIMIT 1),
     'AI Innovations',
     '2023-05-01'::date,
     '2028-04-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.048", "cap_type": "none", "cap_rate": null, "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '19 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd021'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 106' LIMIT 1),
     'Digital Marketing Agency',
     '2023-06-01'::date,
     '2028-05-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.053", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '18 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd022'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 107' LIMIT 1),
     'Management Consultants',
     '2023-07-01'::date,
     '2028-06-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.045", "cap_type": "non_cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '17 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd023'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 108' LIMIT 1),
     'Financial Planning Services',
     '2023-08-01'::date,
     '2028-07-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.050", "cap_type": "cumulative", "cap_rate": "0.06", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '16 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd024'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 109' LIMIT 1),
     'Legal Tech Startup',
     '2023-09-01'::date,
     '2028-08-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.042", "cap_type": "non_cumulative", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '15 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd025'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc002'::uuid AND unit_number = 'Suite 110' LIMIT 1),
     'HR Solutions Group',
     '2023-10-01'::date,
     '2028-09-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.046", "cap_type": "cumulative_compounding", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '14 months',
     NOW())
ON CONFLICT (id) DO NOTHING;

-- Retail Plaza Leases (8 total) - Beta Real Estate Holdings
-- These will be linked to tenant users for tenant portal testing
INSERT INTO leases (id, property_id, unit_id, tenant_name, start_date, end_date, status, recovery_profile, created_at, updated_at)
VALUES
    ('dddddddd-dddd-dddd-dddd-ddddddddd026'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 1' LIMIT 1),
     'Sarah''s Retail Store #1',
     '2023-01-01'::date,
     '2028-12-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.082", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '1 year',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd027'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 2' LIMIT 1),
     'Mike''s Coffee Shop',
     '2023-02-01'::date,
     '2028-01-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.075", "cap_type": "non_cumulative", "cap_rate": "0.06", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '11 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd028'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 3' LIMIT 1),
     'Lisa''s Hair Salon',
     '2023-03-01'::date,
     '2028-02-28'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.068", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '10 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd029'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 4' LIMIT 1),
     'Sarah''s Retail Store #2',
     '2023-04-01'::date,
     '2028-03-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.090", "cap_type": "cumulative", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '9 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd030'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 5' LIMIT 1),
     'David''s Fitness Center',
     '2023-05-01'::date,
     '2028-04-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.12", "cap_type": "non_cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '8 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd031'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 6' LIMIT 1),
     'Pet Supply Store',
     '2023-06-01'::date,
     '2028-05-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.070", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '7 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd032'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 7' LIMIT 1),
     'Sarah''s Retail Store #3',
     '2023-07-01'::date,
     '2028-06-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.085", "cap_type": "cumulative_compounding", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '6 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd033'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc003'::uuid AND unit_number = 'Store 8' LIMIT 1),
     'Electronics Boutique',
     '2023-08-01'::date,
     '2028-07-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.073", "cap_type": "none", "cap_rate": null, "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 months',
     NOW())
ON CONFLICT (id) DO NOTHING;

-- Medical Office Building Leases (5 total) - Gamma Commercial Group
-- Edge case testing: large tenant, micro tenant, high caps, excluded pools
INSERT INTO leases (id, property_id, unit_id, tenant_name, start_date, end_date, status, recovery_profile, created_at, updated_at)
VALUES
    ('dddddddd-dddd-dddd-dddd-ddddddddd034'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid AND unit_number = 'Suite 100' LIMIT 1),
     'Primary Care Center',
     '2023-01-01'::date,
     '2033-12-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.20", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '6 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd035'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid AND unit_number = 'Suite 200' LIMIT 1),
     'Specialty Clinic',
     '2023-02-01'::date,
     '2028-01-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.18", "cap_type": "non_cumulative", "cap_rate": "0.10", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd036'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid AND unit_number = 'Suite 300' LIMIT 1),
     'Dental Office',
     '2023-03-01'::date,
     '2028-02-28'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.16", "cap_type": "cumulative", "cap_rate": "0.08", "admin_fee_percentage": "0.15", "excluded_pools": ["insurance"]}'::jsonb,
     NOW() - INTERVAL '4 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd037'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid AND unit_number = 'Suite 400' LIMIT 1),
     'Physical Therapy',
     '2023-04-01'::date,
     '2028-03-31'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.15", "cap_type": "none", "cap_rate": null, "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '3 months',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd038'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc004'::uuid AND unit_number = 'Suite 500' LIMIT 1),
     'Radiology Services - Small',
     '2023-05-01'::date,
     '2028-04-30'::date,
     'active',
     '{"base_year": 2023, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.005", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": ["operating"]}'::jsonb,
     NOW() - INTERVAL '2 months',
     NOW())
ON CONFLICT (id) DO NOTHING;

-- Class A Office Tower Leases (10 total) - Delta Development Corp
-- All started in 2019 for 6-year multi-year analysis testing
INSERT INTO leases (id, property_id, unit_id, tenant_name, start_date, end_date, status, recovery_profile, created_at, updated_at)
VALUES
    ('dddddddd-dddd-dddd-dddd-ddddddddd039'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1001' LIMIT 1),
     'Fortune 500 Regional HQ',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.095", "cap_type": "cumulative", "cap_rate": "0.03", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd040'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1101' LIMIT 1),
     'Global Law Firm',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.088", "cap_type": "cumulative", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd041'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1201' LIMIT 1),
     'Investment Bank',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.092", "cap_type": "cumulative_compounding", "cap_rate": "0.03", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd042'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1301' LIMIT 1),
     'Tech Unicorn',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.098", "cap_type": "non_cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd043'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1401' LIMIT 1),
     'Consulting Giants',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.086", "cap_type": "cumulative", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd044'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1501' LIMIT 1),
     'Private Equity Fund',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.075", "cap_type": "cumulative", "cap_rate": "0.03", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd045'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1601' LIMIT 1),
     'Architecture Firm',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.082", "cap_type": "non_cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd046'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1701' LIMIT 1),
     'Accounting Firm',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.090", "cap_type": "cumulative_compounding", "cap_rate": "0.04", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd047'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1801' LIMIT 1),
     'Engineering Consultants',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.084", "cap_type": "cumulative", "cap_rate": "0.05", "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW()),
    ('dddddddd-dddd-dddd-dddd-ddddddddd048'::uuid,
     'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid,
     (SELECT id FROM units WHERE property_id = 'cccccccc-cccc-cccc-cccc-ccccccccc005'::uuid AND unit_number = '1901' LIMIT 1),
     'Venture Capital',
     '2019-01-01'::date,
     '2029-12-31'::date,
     'active',
     '{"base_year": 2019, "base_year_amount": null, "gross_up_base_year": true, "pro_rata_share": "0.078", "cap_type": "none", "cap_rate": null, "admin_fee_percentage": "0.15", "excluded_pools": []}'::jsonb,
     NOW() - INTERVAL '5 years',
     NOW())
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
    RAISE NOTICE '   Created 48 leases across 5 properties';
    RAISE NOTICE '   - 15 Downtown Tower leases';
    RAISE NOTICE '   - 10 Suburban Office leases';
    RAISE NOTICE '   - 8 Retail Plaza leases (linked to tenant users)';
    RAISE NOTICE '   - 5 Medical Building leases (edge cases)';
    RAISE NOTICE '   - 10 Class A Tower leases (2019-2024 multi-year)';
END $$;

-- NOTE: This file is INCOMPLETE
-- Due to file size constraints, this demonstrates Section 6 only
-- Sections 7-23 need to be added following the same pattern from the plan
