/**
 * Style Dictionary configuration
 * Reads design-tokens.json and generates:
 *   - frontend/src/generated/tokens.css  (CSS custom properties)
 *   - backend/app/services/email/tokens.py  (Python constants)
 *
 * Run: cd frontend && npm run tokens
 */

const path = require("path");
const fs = require("fs");

const tokens = JSON.parse(
  fs.readFileSync(path.join(__dirname, "design-tokens.json"), "utf8")
);

// ─── CSS Output ────────────────────────────────────────────────────────────────

function buildCSSTokens() {
  const lines = ["/* AUTO-GENERATED by Style Dictionary - edit design-tokens.json instead */",
    ":root {",
  ];

  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`  --color-${key}: ${value.hsl};`);
  }

  for (const [key, value] of Object.entries(tokens.radii)) {
    lines.push(`  --radius-${key}: ${value};`);
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}

// ─── Python Output ─────────────────────────────────────────────────────────────

function toPythonName(key) {
  // "text-primary" -> "TEXT_PRIMARY", "2xl" -> "2XL", etc.
  // Keys that start with a digit (e.g. "2xl") produce names like "2XL" which
  // would be invalid Python identifiers on their own, but all callers prefix
  // them (SPACE_2XL, RADIUS_2XL) so the full identifier is always valid.
  return key.replace(/-/g, "_").toUpperCase();
}

function buildPythonTokens() {
  const lines = [
    "# AUTO-GENERATED by Style Dictionary - edit design-tokens.json instead",
    "",
  ];

  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`${toPythonName(key)} = "${value.hex}"`);
  }

  lines.push(`FONT_FAMILY = "${tokens.typography.fontFamily}"  # noqa: E501`);

  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`SPACE_${toPythonName(key)} = "${value}"`);
  }

  for (const [key, value] of Object.entries(tokens.radii)) {
    lines.push(`RADIUS_${toPythonName(key)} = "${value}"`);
  }

  // Convenience: white text for use on dark backgrounds
  lines.push(`TEXT_INVERSE = "#ffffff"`);

  lines.push("");
  return lines.join("\n");
}

// ─── Write files ────────────────────────────────────────────────────────────────

const cssOut = path.join(__dirname, "frontend", "src", "generated", "tokens.css");
const pyOut = path.join(
  __dirname,
  "backend",
  "app",
  "services",
  "email",
  "tokens.py"
);

fs.mkdirSync(path.dirname(cssOut), { recursive: true });
fs.writeFileSync(cssOut, buildCSSTokens());
console.log(`✓ Wrote ${path.relative(__dirname, cssOut)}`);

fs.writeFileSync(pyOut, buildPythonTokens());
console.log(`✓ Wrote ${path.relative(__dirname, pyOut)}`);

const marketingCssOut = path.join(__dirname, "marketing", "src", "generated", "tokens.css");
fs.mkdirSync(path.dirname(marketingCssOut), { recursive: true });
fs.writeFileSync(marketingCssOut, buildCSSTokens());
console.log(`✓ Wrote ${path.relative(__dirname, marketingCssOut)}`);
