"""Organization domain models for multi-tenant isolation.

These models define the organization entity that serves as the root
of all tenant-scoped data. Every major entity in the system belongs
to exactly one organization.
"""

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SubscriptionStatus(str, Enum):
    """Subscription status of an organization."""

    ACTIVE = "active"
    TRIAL = "trial"
    SUSPENDED = "suspended"
    CANCELLED = "cancelled"


class OrganizationSettings(BaseModel):
    """Flexible settings stored as JSONB.

    These settings allow per-organization customization without
    requiring schema changes.
    """

    timezone: str = Field(
        default="America/New_York",
        description="IANA timezone for display purposes",
    )
    default_currency: str = Field(
        default="USD",
        description="ISO 4217 currency code",
    )
    fiscal_year_end_month: int = Field(
        default=12,
        ge=1,
        le=12,
        description="Month (1-12) when fiscal year ends",
    )
    contact_name: str | None = Field(None, max_length=255)
    contact_title: str | None = Field(None, max_length=255)
    contact_company: str | None = Field(None, max_length=255)
    contact_phone: str | None = Field(None, max_length=50)
    contact_email: str | None = Field(None, max_length=255)
    contact_address: str | None = Field(None, max_length=1000)


class OrganizationBase(BaseModel):
    """Base fields for Organization."""

    name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Organization display name",
    )
    subscription_status: SubscriptionStatus = Field(
        default=SubscriptionStatus.TRIAL,
        description="Current subscription status",
    )
    settings: OrganizationSettings = Field(
        default_factory=lambda: OrganizationSettings(),
        description="Organization-specific settings",
    )


class OrganizationCreate(OrganizationBase):
    """DTO for creating an organization.

    Inherits all base fields. ID and timestamps are
    generated by the database.
    """

    pass


class OrganizationUpdate(BaseModel):
    """DTO for updating an organization (all fields optional).

    Only provided fields will be updated; others remain unchanged.
    """

    name: str | None = Field(
        None,
        min_length=1,
        max_length=255,
        description="Organization display name",
    )
    subscription_status: SubscriptionStatus | None = Field(
        None,
        description="Current subscription status",
    )
    settings: OrganizationSettings | None = Field(
        None,
        description="Organization-specific settings",
    )


class Organization(OrganizationBase):
    """Full organization model from database.

    Includes all base fields plus database-generated fields.
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID = Field(description="Unique organization identifier")
    created_at: datetime = Field(description="When organization was created")
    updated_at: datetime = Field(description="When organization was last modified")


class OrganizationSettingsUpdate(BaseModel):
    """Request schema for partial settings update.

    All fields are optional - only provided fields will be updated.
    """

    timezone: str | None = Field(
        None,
        description="IANA timezone for display purposes",
    )
    default_currency: str | None = Field(
        None,
        description="ISO 4217 currency code",
    )
    fiscal_year_end_month: int | None = Field(
        None,
        ge=1,
        le=12,
        description="Month (1-12) when fiscal year ends",
    )
    contact_name: str | None = Field(None, max_length=255)
    contact_title: str | None = Field(None, max_length=255)
    contact_company: str | None = Field(None, max_length=255)
    contact_phone: str | None = Field(None, max_length=50)
    contact_email: str | None = Field(None, max_length=255)
    contact_address: str | None = Field(None, max_length=1000)


class OrganizationSettingsResponse(OrganizationSettings):
    """Response schema for organization settings.

    Extends OrganizationSettings with organization context.
    """

    organization_id: UUID = Field(description="Organization this settings belongs to")
