#!/usr/bin/env python
"""
Validate OpenAPI spec against official schema.

This script validates the OpenAPI specification generated by the FastAPI
application against the official OpenAPI 3.0/3.1 schema.

Usage:
    python scripts/validate_openapi.py

The script will:
1. Try to fetch the spec from a running server at http://localhost:8000
2. Fall back to generating the spec directly from the app if server is unavailable
3. Validate the spec against the OpenAPI schema
4. Exit with code 0 if valid, 1 if invalid
"""

import sys

import requests
from openapi_spec_validator import validate
from openapi_spec_validator.validation.exceptions import OpenAPIValidationError


def fetch_spec_from_server(url: str = "http://localhost:8000/openapi.json") -> dict:
    """Fetch OpenAPI spec from running server.

    Args:
        url: The URL to fetch the OpenAPI spec from

    Returns:
        The OpenAPI spec as a dictionary

    Raises:
        requests.RequestException: If the request fails
    """
    response = requests.get(url, timeout=10)
    response.raise_for_status()
    return response.json()


def generate_spec_from_app() -> dict:
    """Generate OpenAPI spec directly from the FastAPI app.

    Returns:
        The OpenAPI spec as a dictionary
    """
    from app.main import app

    return app.openapi()


def main() -> int:
    """Fetch and validate OpenAPI spec.

    Returns:
        0 if spec is valid, 1 if invalid
    """
    # Try to fetch from running server first
    try:
        print("Attempting to fetch spec from http://localhost:8000/openapi.json...")
        spec = fetch_spec_from_server()
        print("Successfully fetched spec from server.")
    except requests.RequestException as e:
        print(f"Could not fetch from server ({e}), generating from app...")
        spec = generate_spec_from_app()
        print("Successfully generated spec from app.")

    # Validate against OpenAPI schema
    try:
        validate(spec)
        print("\n" + "=" * 50)
        print("OpenAPI spec is valid!")
        print("=" * 50)
        print(f"\nSpec version: {spec.get('openapi', 'unknown')}")
        print(f"API title: {spec.get('info', {}).get('title', 'unknown')}")
        print(f"API version: {spec.get('info', {}).get('version', 'unknown')}")
        print(f"Number of paths: {len(spec.get('paths', {}))}")

        # List paths
        paths = list(spec.get("paths", {}).keys())
        if paths:
            print("\nDefined paths:")
            for path in sorted(paths):
                methods = list(spec["paths"][path].keys())
                print(f"  {path}: {', '.join(methods)}")

        return 0

    except OpenAPIValidationError as e:
        print("\n" + "=" * 50)
        print("OpenAPI spec validation FAILED!")
        print("=" * 50)
        print(f"\nError: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
