"""Tests for TenantInvitationService.

These tests verify invitation token validation and tenant signup flow,
including all error cases and the complete 6-step signup process.
"""

from datetime import UTC, datetime, timedelta
from unittest.mock import MagicMock, patch
from uuid import uuid4

import pytest

from app.exceptions.handlers import InvalidInvitationTokenError
from app.legal_terms import TERMS_HASH, TERMS_VERSION
from app.services.tenant_invitation import TenantInvitationService


def make_valid_invitation_data() -> dict:
    """Create valid invitation data for testing."""
    # Use UUID-format token to pass length/format validation (AS-7 fix)
    valid_token = str(uuid4())  # 36 chars, alphanumeric + hyphens
    return {
        "id": str(uuid4()),
        "token": valid_token,
        "email": "tenant@example.com",
        "organization_id": str(uuid4()),
        "lease_id": str(uuid4()),
        "expires_at": (datetime.now(UTC) + timedelta(days=7)).isoformat(),
        "used_at": None,
        "used_by_user_id": None,
        "revoked_at": None,
        "created_at": datetime.now(UTC).isoformat(),
    }


# Valid token for tests (meets min length of 32 chars)
VALID_TEST_TOKEN = "valid-test-token-12345678901234567890"


def current_terms_kwargs() -> dict[str, str | bool]:
    """Return current legal acceptance fields for direct service calls."""
    return {
        "accepted_terms": True,
        "terms_version": TERMS_VERSION,
        "terms_hash": TERMS_HASH,
    }


@pytest.fixture
def mock_db():
    """Mock Supabase client."""
    return MagicMock()


@pytest.fixture
def mock_admin():
    """Mock Supabase admin client."""
    return MagicMock()


@pytest.fixture
def service(mock_db, mock_admin):
    """Create TenantInvitationService with mocked dependencies."""
    with patch(
        "app.services.tenant_invitation.get_supabase_admin", return_value=mock_admin
    ):
        return TenantInvitationService(db=mock_db)


class TestValidateToken:
    """Tests for validate_token method."""

    async def test_valid_token_success(self, service, mock_admin) -> None:
        """Valid token passes validation."""
        invitation_data = make_valid_invitation_data()
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        # Use the token from the invitation data (UUID format, 36 chars)
        result = await service.validate_token(invitation_data["token"])

        assert result == invitation_data
        mock_admin.table.assert_called_with("tenant_invitations")

    async def test_valid_token_allows_urlsafe_underscore(
        self, service, mock_admin
    ) -> None:
        """Tenant invite validation accepts tokens generated by token_urlsafe."""
        invitation_data = make_valid_invitation_data()
        invitation_data["token"] = "valid_token_with_underscore_1234567890"
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = MagicMock(
            data=[invitation_data]
        )

        result = await service.validate_token(invitation_data["token"])

        assert result == invitation_data

    async def test_valid_token_uses_admin_client_for_public_signup(
        self, service, mock_db, mock_admin
    ) -> None:
        """Public invitation validation bypasses tenant_invitations RLS safely."""
        invitation_data = make_valid_invitation_data()
        admin_result = MagicMock()
        admin_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            admin_result
        )

        result = await service.validate_token(invitation_data["token"])

        assert result == invitation_data
        mock_admin.table.assert_called_with("tenant_invitations")
        mock_db.table.assert_not_called()

    async def test_token_not_found(self, service, mock_db) -> None:
        """Token not found raises error."""
        mock_result = MagicMock()
        mock_result.data = []
        mock_db.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        with pytest.raises(InvalidInvitationTokenError) as exc_info:
            await service.validate_token("invalid_token")
        assert "not_found" in str(exc_info.value)

    async def test_token_revoked(self, service, mock_admin) -> None:
        """Revoked token raises error."""
        invitation_data = make_valid_invitation_data()
        invitation_data["revoked_at"] = datetime.now(UTC).isoformat()
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        with pytest.raises(InvalidInvitationTokenError) as exc_info:
            await service.validate_token(invitation_data["token"])
        assert "revoked" in str(exc_info.value)

    async def test_token_already_used(self, service, mock_admin) -> None:
        """Already used token raises error."""
        invitation_data = make_valid_invitation_data()
        invitation_data["used_at"] = datetime.now(UTC).isoformat()
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        with pytest.raises(InvalidInvitationTokenError) as exc_info:
            await service.validate_token(invitation_data["token"])
        assert "used" in str(exc_info.value)

    async def test_token_expired(self, service, mock_admin) -> None:
        """Expired token raises error."""
        invitation_data = make_valid_invitation_data()
        # Set expiration to 7 days ago
        invitation_data["expires_at"] = (
            datetime.now(UTC) - timedelta(days=7)
        ).isoformat()
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        with pytest.raises(InvalidInvitationTokenError) as exc_info:
            await service.validate_token(invitation_data["token"])
        assert "expired" in str(exc_info.value)

    async def test_token_with_timezone_suffix(self, service, mock_admin) -> None:
        """Token expiration with Z suffix is parsed correctly."""
        invitation_data = make_valid_invitation_data()
        # ISO format with Z suffix (use UTC datetime without microseconds to avoid double timezone)
        future_date = datetime.now(UTC) + timedelta(days=7)
        invitation_data["expires_at"] = (
            future_date.replace(microsecond=0).isoformat().replace("+00:00", "Z")
        )
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        result = await service.validate_token(invitation_data["token"])
        assert result == invitation_data


class TestCompleteSignup:
    """Tests for complete_signup method."""

    async def test_complete_signup_success(self, service, mock_db, mock_admin) -> None:
        """Full signup flow succeeds with valid data."""
        invitation_data = make_valid_invitation_data()

        # Mock validate_token
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        # Mock auth user creation
        mock_user = MagicMock()
        mock_user.id = str(uuid4())
        mock_auth_response = MagicMock()
        mock_auth_response.user = mock_user
        service.supabase_admin.auth.admin.create_user = MagicMock(
            return_value=mock_auth_response
        )

        # Mock tenant_user creation
        tenant_user_data = {
            "id": str(uuid4()),
            "user_id": str(mock_user.id),
            "contact_name": "John Doe",
        }
        mock_tenant_result = MagicMock()
        mock_tenant_result.data = [tenant_user_data]
        service.supabase_admin.table.return_value.insert.return_value.execute.return_value = (
            mock_tenant_result
        )

        # Mock lease link creation
        mock_lease_result = MagicMock()
        mock_lease_result.data = [{"id": str(uuid4())}]

        # Mock invitation update
        mock_update_result = MagicMock()
        mock_update_result.data = [invitation_data]

        # Mock sign in
        mock_session = MagicMock()
        mock_session.access_token = "access_token_123"
        mock_session.refresh_token = "refresh_token_456"
        mock_signin_response = MagicMock()
        mock_signin_response.session = mock_session
        service.supabase_admin.auth.sign_in_with_password = MagicMock(
            return_value=mock_signin_response
        )

        # Execute - use the token from invitation data (UUID format)
        result = await service.complete_signup(
            token=invitation_data["token"],
            password="SecurePassword123!",
            contact_name="John Doe",
            **current_terms_kwargs(),
        )

        # Verify
        tenant_user, access_token, refresh_token = result
        assert access_token == "access_token_123"
        assert refresh_token == "refresh_token_456"
        assert tenant_user is not None

    async def test_complete_signup_updates_profile_to_tenant_role(
        self, service, mock_admin
    ) -> None:
        """Tenant signup rewrites the auth trigger profile into tenant context."""
        invitation_data = make_valid_invitation_data()
        invite_result = MagicMock()
        invite_result.data = [invitation_data]

        mock_user = MagicMock()
        mock_user.id = str(uuid4())
        mock_auth_response = MagicMock()
        mock_auth_response.user = mock_user
        service.supabase_admin.auth.admin.create_user = MagicMock(
            return_value=mock_auth_response
        )

        tenant_user_data = {
            "id": str(uuid4()),
            "user_id": str(mock_user.id),
            "organization_id": invitation_data["organization_id"],
            "contact_name": "John Doe",
            "contact_email": invitation_data["email"],
            "created_at": datetime.now(UTC).isoformat(),
        }
        tenant_user_result = MagicMock()
        tenant_user_result.data = [tenant_user_data]
        write_result = MagicMock()
        write_result.data = [{"ok": True}]

        query_builders: dict[str, MagicMock] = {}

        def table(name: str) -> MagicMock:
            builder = MagicMock()
            query_builders[name] = builder
            if name == "tenant_invitations":
                builder.select.return_value.eq.return_value.execute.return_value = (
                    invite_result
                )
                builder.update.return_value.eq.return_value.execute.return_value = (
                    write_result
                )
            elif name == "tenant_users":
                builder.insert.return_value.execute.return_value = tenant_user_result
            else:
                builder.insert.return_value.execute.return_value = write_result
                builder.upsert.return_value.execute.return_value = write_result
            return builder

        mock_admin.table.side_effect = table

        mock_session = MagicMock()
        mock_session.access_token = "access_token_123"
        mock_session.refresh_token = "refresh_token_456"
        mock_signin_response = MagicMock()
        mock_signin_response.session = mock_session
        service.supabase_admin.auth.sign_in_with_password = MagicMock(
            return_value=mock_signin_response
        )

        await service.complete_signup(
            token=invitation_data["token"],
            password="SecurePassword123!",
            contact_name="John Doe",
            **current_terms_kwargs(),
        )

        users_builder = query_builders["users"]
        users_builder.upsert.assert_called_once()
        profile_payload = users_builder.upsert.call_args.args[0]
        assert profile_payload["id"] == str(mock_user.id)
        assert profile_payload["organization_id"] == invitation_data["organization_id"]
        assert profile_payload["email"] == invitation_data["email"]
        assert profile_payload["full_name"] == "John Doe"
        assert profile_payload["role"] == "tenant"

        lease_link_builder = query_builders["tenant_lease_links"]
        lease_link_builder.insert.assert_called_once()
        lease_link_payload = lease_link_builder.insert.call_args.args[0]
        assert lease_link_payload["tenant_user_id"] == tenant_user_data["id"]
        assert lease_link_payload["lease_id"] == invitation_data["lease_id"]
        assert "id" not in lease_link_payload

    async def test_complete_signup_invalid_token(self, service, mock_db) -> None:
        """Signup fails with invalid token."""
        mock_result = MagicMock()
        mock_result.data = []
        mock_db.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        with pytest.raises(InvalidInvitationTokenError):
            await service.complete_signup(
                token="invalid_token",
                password="SecurePassword123!",
                contact_name="John Doe",
                **current_terms_kwargs(),
            )

    async def test_complete_signup_auth_creation_fails(
        self, service, mock_admin
    ) -> None:
        """Signup fails when auth user creation fails."""
        from fastapi import HTTPException

        invitation_data = make_valid_invitation_data()
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        # Auth creation returns None
        mock_auth_response = MagicMock()
        mock_auth_response.user = None
        service.supabase_admin.auth.admin.create_user = MagicMock(
            return_value=mock_auth_response
        )

        with pytest.raises(HTTPException) as exc_info:
            await service.complete_signup(
                token=invitation_data["token"],
                password="SecurePassword123!",
                contact_name="John Doe",
                **current_terms_kwargs(),
            )
        assert exc_info.value.status_code == 500
        assert "auth user" in str(exc_info.value.detail).lower()

    async def test_complete_signup_tenant_user_creation_fails(
        self, service, mock_admin
    ) -> None:
        """Signup fails when tenant_user creation fails."""
        from fastapi import HTTPException

        invitation_data = make_valid_invitation_data()
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        # Auth creation succeeds
        mock_user = MagicMock()
        mock_user.id = str(uuid4())
        mock_auth_response = MagicMock()
        mock_auth_response.user = mock_user
        service.supabase_admin.auth.admin.create_user = MagicMock(
            return_value=mock_auth_response
        )

        # Tenant user creation returns empty data
        mock_tenant_result = MagicMock()
        mock_tenant_result.data = []
        service.supabase_admin.table.return_value.insert.return_value.execute.return_value = (
            mock_tenant_result
        )

        with pytest.raises(HTTPException) as exc_info:
            await service.complete_signup(
                token=invitation_data["token"],
                password="SecurePassword123!",
                contact_name="John Doe",
                **current_terms_kwargs(),
            )
        assert exc_info.value.status_code == 500
        assert "tenant user" in str(exc_info.value.detail).lower()

    async def test_complete_signup_token_generation_fails(
        self, service, mock_admin
    ) -> None:
        """Signup fails when token generation fails."""
        from fastapi import HTTPException

        invitation_data = make_valid_invitation_data()
        mock_result = MagicMock()
        mock_result.data = [invitation_data]
        mock_admin.table.return_value.select.return_value.eq.return_value.execute.return_value = (
            mock_result
        )

        # Auth creation succeeds
        mock_user = MagicMock()
        mock_user.id = str(uuid4())
        mock_auth_response = MagicMock()
        mock_auth_response.user = mock_user
        service.supabase_admin.auth.admin.create_user = MagicMock(
            return_value=mock_auth_response
        )

        # Tenant user creation succeeds
        tenant_user_data = {"id": str(uuid4()), "user_id": str(mock_user.id)}
        mock_tenant_result = MagicMock()
        mock_tenant_result.data = [tenant_user_data]
        service.supabase_admin.table.return_value.insert.return_value.execute.return_value = (
            mock_tenant_result
        )

        # Sign in returns no session
        mock_signin_response = MagicMock()
        mock_signin_response.session = None
        service.supabase_admin.auth.sign_in_with_password = MagicMock(
            return_value=mock_signin_response
        )

        with pytest.raises(HTTPException) as exc_info:
            await service.complete_signup(
                token=invitation_data["token"],
                password="SecurePassword123!",
                contact_name="John Doe",
                **current_terms_kwargs(),
            )
        assert exc_info.value.status_code == 500
        assert "tokens" in str(exc_info.value.detail).lower()


class TestServiceInitialization:
    """Tests for service initialization."""

    def test_service_initialization(self, mock_db, mock_admin) -> None:
        """Service initializes with db and admin clients."""
        with patch(
            "app.services.tenant_invitation.get_supabase_admin", return_value=mock_admin
        ):
            service = TenantInvitationService(db=mock_db)
            assert service.db == mock_db
            assert service.supabase_admin == mock_admin
