"""
Tenant invitation service for managing invitation tokens and signup flow.

Handles validation of invitation tokens and the complete tenant signup process.
"""

import logging
import secrets
from datetime import UTC, datetime, timedelta
from typing import Any, cast
from uuid import UUID, uuid4

from app.database.client import SupabaseDB, get_supabase_admin
from app.exceptions.handlers import InvalidInvitationTokenError
from app.legal_terms import TERMS_HASH, TERMS_VERSION
from app.services.legal_acceptance import (
    assert_current_terms_acceptance,
    record_terms_acceptance,
)

logger = logging.getLogger(__name__)

# Invitation expiration time
INVITATION_EXPIRY_DAYS = 7


class TenantInvitationService:
    """Business logic for tenant invitations and signup."""

    def __init__(self, db: SupabaseDB):
        self.db = db
        self.supabase_admin = get_supabase_admin()

    # FIX AS-7: Token format/length constraints to prevent DoS
    MAX_TOKEN_LENGTH = 128  # UUIDs are 36 chars, allow some padding
    MIN_TOKEN_LENGTH = 32  # Minimum reasonable token length

    async def validate_token(self, token: str) -> dict[str, Any]:
        """
        Validate invitation token.

        FIX AS-7: Added format/length validation to prevent DoS via long tokens.

        Args:
            token: The invitation token to validate

        Returns:
            TenantInvitation data if valid

        Raises:
            InvalidInvitationTokenError: If token is invalid/expired/used/revoked
        """
        # FIX AS-7: Validate token format before DB query
        # Prevents DoS via extremely long strings that cause table scans
        if not token or not isinstance(token, str):
            raise InvalidInvitationTokenError(reason="not_found")

        token = token.strip()
        if len(token) < self.MIN_TOKEN_LENGTH or len(token) > self.MAX_TOKEN_LENGTH:
            raise InvalidInvitationTokenError(reason="not_found")

        # Only allow URL-safe tokens generated by secrets.token_urlsafe.
        import re

        if not re.match(r"^[a-zA-Z0-9_-]+$", token):
            raise InvalidInvitationTokenError(reason="not_found")

        result = (
            self.supabase_admin.table("tenant_invitations")
            .select("*")
            .eq("token", token)
            .execute()
        )

        if not result.data or len(result.data) == 0:
            raise InvalidInvitationTokenError(reason="not_found")

        # Cast JSON result to dict for type safety
        invitation = cast(dict[str, Any], result.data[0])

        if invitation.get("revoked_at") is not None or invitation.get("is_revoked"):
            raise InvalidInvitationTokenError(reason="revoked")
        if invitation.get("used_at") is not None:
            raise InvalidInvitationTokenError(reason="used")

        expires_at_str = invitation.get("expires_at")
        if expires_at_str:
            # Parse ISO datetime string
            expires_at = datetime.fromisoformat(expires_at_str.replace("Z", "+00:00"))
            if expires_at < datetime.now(UTC):
                raise InvalidInvitationTokenError(reason="expired")

        return invitation

    async def complete_signup(
        self,
        token: str,
        password: str,
        contact_name: str,
        accepted_terms: bool,
        terms_version: str,
        terms_hash: str,
    ) -> tuple[dict[str, Any], str, str]:
        """
        Complete tenant signup.

        Steps:
        1. Validate token
        2. Create Supabase Auth user
        3. Create TenantUser record
        4. Create TenantLeaseLink
        5. Mark invitation used
        6. Generate tokens

        Args:
            token: Invitation token
            password: User password
            contact_name: Tenant contact name

        Returns:
            Tuple of (tenant_user_data, access_token, refresh_token)

        Raises:
            InvalidInvitationTokenError: If token is invalid
            HTTPException: If signup fails
        """
        from fastapi import HTTPException

        assert_current_terms_acceptance(
            accepted_terms, terms_version=terms_version, terms_hash=terms_hash
        )

        # Step 1: Validate token
        invitation = await self.validate_token(token)

        # Step 2: Create Supabase Auth user
        auth_response = self.supabase_admin.auth.admin.create_user(
            {
                "email": invitation["email"],
                "password": password,
                "email_confirm": True,
                "user_metadata": {
                    "contact_name": contact_name,
                    "invited_by": "tenant_portal",
                    "accepted_terms": True,
                    "terms_version": TERMS_VERSION,
                    "terms_hash": TERMS_HASH,
                },
            }
        )

        if auth_response.user is None:
            raise HTTPException(500, "Failed to create auth user")

        auth_user_id = auth_response.user.id

        self.supabase_admin.table("users").upsert(
            {
                "id": str(auth_user_id),
                "organization_id": invitation["organization_id"],
                "email": invitation["email"],
                "full_name": contact_name,
                "role": "tenant",
            }
        ).execute()

        # Step 3: Create TenantUser
        tenant_user_data = {
            "id": str(uuid4()),
            "user_id": str(auth_user_id),
            "organization_id": invitation["organization_id"],
            "contact_name": contact_name,
            "contact_email": invitation["email"],
            "created_at": datetime.now(UTC).isoformat(),
        }
        tenant_user_result = (
            self.supabase_admin.table("tenant_users").insert(tenant_user_data).execute()
        )
        tenant_user = (
            cast(dict[str, Any], tenant_user_result.data[0])
            if tenant_user_result.data
            else None
        )
        if not tenant_user:
            raise HTTPException(500, "Failed to create tenant user")

        record_terms_acceptance(
            self.supabase_admin,
            user_id=str(auth_user_id),
            organization_id=str(invitation["organization_id"]),
            source="tenant_invitation_signup",
        )

        # Step 4: Create TenantLeaseLink
        lease_link_data = {
            "tenant_user_id": tenant_user["id"],
            "lease_id": invitation["lease_id"],
            "created_at": datetime.now(UTC).isoformat(),
        }
        self.supabase_admin.table("tenant_lease_links").insert(
            lease_link_data
        ).execute()

        # Step 5: Mark invitation used. Keep this conditional so concurrent
        # signup attempts cannot both consume the same token.
        update_result = (
            self.supabase_admin.table("tenant_invitations")
            .update({"used_at": datetime.now(UTC).isoformat()})
            .eq("token", token)
            .eq("organization_id", invitation["organization_id"])
            .is_("used_at", "null")
            .execute()
        )
        if not update_result.data:
            raise InvalidInvitationTokenError(reason="used")

        # Step 6: Generate tokens
        sign_in_response = self.supabase_admin.auth.sign_in_with_password(
            {
                "email": invitation["email"],
                "password": password,
            }
        )

        if sign_in_response.session is None:
            raise HTTPException(500, "Failed to generate tokens")

        return (
            tenant_user,
            sign_in_response.session.access_token,
            sign_in_response.session.refresh_token,
        )

    async def create_invitation(
        self,
        email: str,
        lease_id: UUID,
        invited_by: UUID,
        organization_id: UUID,
    ) -> dict[str, Any]:
        """
        Create a tenant invitation and store it in the database.

        Generates a secure token and sets expiration to 7 days from now.

        Args:
            email: Tenant's email address
            lease_id: UUID of the lease to grant access to
            invited_by: UUID of the admin creating the invitation
            organization_id: UUID of the organization

        Returns:
            The created invitation record
        """
        # Generate secure token
        token = secrets.token_urlsafe(32)

        # Calculate expiration
        expires_at = datetime.now(UTC) + timedelta(days=INVITATION_EXPIRY_DAYS)

        # Create invitation record
        invitation_data = {
            "id": str(uuid4()),
            "email": email,
            "lease_id": str(lease_id),
            "token": token,
            "organization_id": str(organization_id),
            "invited_by": str(invited_by),
            "expires_at": expires_at.isoformat(),
            "created_at": datetime.now(UTC).isoformat(),
            "used_at": None,
            "is_revoked": False,
        }

        result = self.db.table("tenant_invitations").insert(invitation_data).execute()

        if not result.data or len(result.data) == 0:
            from fastapi import HTTPException

            raise HTTPException(500, "Failed to create invitation")

        logger.info(
            "Created tenant invitation for %s to lease %s",
            email,
            str(lease_id),
        )

        return cast(dict[str, Any], result.data[0])
