import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]  # scripts/oneoff -> repo root
dest = REPO_ROOT / "backend" / "app" / "api" / "routes" / "webhooks.py"
L = []
def a(s): L.append(s)
a("\"\"\"Stripe webhook handlers.")
a("")
a("These endpoints receive events from Stripe and update local database state.")
a("All handlers must be idempotent - processing the same event twice should")
a("produce the same result.")
a("\"\"\"")
a("")
a("import logging")
a("from datetime import UTC, datetime")
a("from typing import Any, cast")
a("")
a("import stripe")
a("from fastapi import APIRouter, Depends, HTTPException, Request")
a("")
a("from app.database import get_supabase_admin")
a("from app.database.client import SupabaseDB")
a("from app.services.billing.config import get_stripe_settings")
a("")
a("logger = logging.getLogger(__name__)")
a("")
a("router = APIRouter(prefix=\"/webhooks\", tags=[\"webhooks\"])")
a("")
a("")
a("@router.post(\"/stripe\")")
a("async def handle_stripe_webhook(")
a("    request: Request,")
a("    db: SupabaseDB = Depends(get_supabase_admin),")
a(") -> dict[str, Any]:")
a("    \"\"\"")
a("    Handle incoming Stripe webhook events.")
a("")
a("    Verifies signature and dispatches to appropriate handler.")
a("    \"\"\"")
a("    # Get raw body for signature verification")
a("    payload = await request.body()")
a("    sig_header = request.headers.get(\"stripe-signature\")")
a("")
a("    if not sig_header:")
a("        raise HTTPException(400, \"Missing stripe-signature header\")")
a("")
a("    settings = get_stripe_settings()")
a("")
a("    try:")
a("        event = stripe.Webhook.construct_event(  # type: ignore[no-untyped-call]")
a("            payload,")
a("            sig_header,")
a("            settings.stripe_webhook_secret,")
a("        )")
a("    except ValueError:")
a("        raise HTTPException(400, \"Invalid payload\")")
a("    except stripe.error.SignatureVerificationError:")
a("        raise HTTPException(400, \"Invalid signature\")")
a("")
a("    # Log received webhook event")
a("    logger.info(f\"Received Stripe webhook: {event.type} (id: {event.id})\")")
a("")
a("    # Deduplicate: atomically claim event before dispatch")
a("    claimed = await _claim_webhook_event(db, event.id, event.type)")
a("    if not claimed:")
a("        logger.info(f\"Duplicate webhook event {event.id} skipped\")")
a("        return {\"received\": True}")
a("")
a("    # Dispatch to handler based on event type")
a("    handlers = {")
a("        \"customer.subscription.created\": handle_subscription_created,")
a("        \"customer.subscription.updated\": handle_subscription_updated,")
a("        \"customer.subscription.deleted\": handle_subscription_deleted,")
a("        \"invoice.paid\": handle_invoice_paid,")
a("        \"invoice.payment_failed\": handle_invoice_payment_failed,")
a("        \"invoice.created\": handle_invoice_created,")
a("    }")
a("")
a("    handler = handlers.get(event.type)")
a("    if handler:")
a("        logger.info(f\"Dispatching to handler for {event.type}\")")
a("        event_data = cast(dict[str, Any], event.data.object)")
a("        try:")
a("            await handler(event_data, db)")
a("            await _complete_webhook_event(db, event.id)")
a("            logger.info(f\"Successfully processed {event.type}\")")
a("        except Exception:")
a("            await _release_webhook_event(db, event.id)")
a("            raise")
a("    else:")
a("        logger.warning(f\"No handler for event type: {event.type}\")")
a("        await _complete_webhook_event(db, event.id)")
a("")
a("    return {\"received\": True}")
a("")
a("")
a("async def handle_subscription_created(sub: dict[str, Any], db: SupabaseDB) -> None:")
a("    \"\"\"Handle new subscription creation.\"\"\"")
a("    logger.info(f\"Processing subscription.created: {sub.get('id')}\")")
a("    logger.info(f\"Subscription metadata: {sub.get('metadata', {})}\")")
a("    logger.info(f\"Customer ID: {sub.get('customer')}\")")
a("")
a("    org_id = sub.get(\"metadata\", {}).get(\"organization_id\")")
a("    logger.info(f\"Org ID from metadata: {org_id}\")")
a("")
a("    if not org_id:")
a("        # Try to find org by customer ID")
a("        customer_id = sub.get(\"customer\")")
a("        if customer_id:")
a("            org_id = await _get_org_by_customer(str(customer_id), db)")
a("        logger.info(f\"Org ID from customer lookup: {org_id}\")")
a("")
a("    if not org_id:")
a("        logger.warning(")
a("            f\"Cannot link subscription {sub.get('id')} - no organization found\"")
a("        )")
a("        return  # Cannot link subscription without org")
a("")
a("    # Extract building_count from subscription item quantity")
a("    items = sub.get(\"items\", {})")
a("    items_data = items.get(\"data\", []) if isinstance(items, dict) else []")
a("    building_count = items_data[0].get(\"quantity\", 1) if items_data else 1")
a("    price = items_data[0].get(\"price\", {}) if items_data else {}")
a("    price_id = price.get(\"id\") if isinstance(price, dict) else None")
a("")
a("    logger.info(")
a("        f\"Creating subscription for org {org_id}: \"")
a("        f\"plan={price_id}, buildings={building_count}\"")
a("    )")
a("    logger.info(f\"Subscription keys: {list(sub.keys())}\")")
a("")
a("    # Access period timestamps - use start_date and billing_cycle_anchor as fallbacks")
a("    # In subscription.created event, current_period fields may not be set yet")
a("    period_start = (")
a("        sub.get(\"current_period_start\") or sub.get(\"start_date\") or sub.get(\"created\")")
a("    )")
a("    period_end = sub.get(\"current_period_end\") or sub.get(\"billing_cycle_anchor\")")
a("    logger.info(")
a("        f\"current_period_start: {period_start}, current_period_end: {period_end}\"")
a("    )")
a("")
a("    # Use upsert for idempotency")
a("    result = (")
a("        db.table(\"subscriptions\")")
a("        .upsert(")
a("            {")
a("                \"organization_id\": org_id,")
a("                \"stripe_subscription_id\": sub.get(\"id\"),")
a("                \"stripe_customer_id\": sub.get(\"customer\"),")
a("                \"plan\": _map_price_to_plan(price_id) if price_id else \"growth\",")
a("                \"status\": _map_subscription_status(sub.get(\"status\")),")
a("                \"building_count\": building_count,")
a("                \"current_period_start\": (")
a("                    datetime.fromtimestamp(int(period_start), tz=UTC).isoformat()")
a("                    if period_start")
a("                    else datetime.now(UTC).isoformat()")
a("                ),")
a("                \"current_period_end\": (")
a("                    datetime.fromtimestamp(int(period_end), tz=UTC).isoformat()")
a("                    if period_end")
a("                    else datetime.now(UTC).isoformat()")
a("                ),")
a("                \"cancel_at_period_end\": sub.get(\"cancel_at_period_end\", False),")
a("                \"updated_at\": datetime.now(UTC).isoformat(),")
a("            },")
a("            on_conflict=\"organization_id\",")
a("        )")
a("        .execute()")
a("    )")
a("")
a("    logger.info(f\"Subscription created successfully: {result.data}\")")
a("")
a("")
a("async def handle_subscription_updated(sub: dict[str, Any], db: SupabaseDB) -> None:")
a("    \"\"\"Handle subscription updates (plan, status, quantity changes, etc.).\"\"\"")
a("    # Extract building_count from subscription item quantity")
a("    items = sub.get(\"items\", {})")
a("    items_data = items.get(\"data\", []) if isinstance(items, dict) else []")
a("    building_count = items_data[0].get(\"quantity\", 1) if items_data else 1")
a("    price = items_data[0].get(\"price\", {}) if items_data else {}")
a("    price_id = price.get(\"id\") if isinstance(price, dict) else None")
a("")
a("    # Access period timestamps - use fallbacks")
a("    period_start = (")
a("        sub.get(\"current_period_start\") or sub.get(\"start_date\") or sub.get(\"created\")")
a("    )")
a("    period_end = sub.get(\"current_period_end\") or sub.get(\"billing_cycle_anchor\")")
a("")
a("    # Build update dict - only include period fields if they exist")
a("    update_data: dict[str, Any] = {")
a("        \"plan\": _map_price_to_plan(price_id) if price_id else \"growth\",")
a("        \"status\": _map_subscription_status(sub.get(\"status\")),")
a("        \"building_count\": building_count,")
a("        \"cancel_at_period_end\": sub.get(\"cancel_at_period_end\", False),")
a("        \"updated_at\": datetime.now(UTC).isoformat(),")
a("    }")
a("")
a("    if period_start:")
a("        update_data[\"current_period_start\"] = datetime.fromtimestamp(")
a("            int(period_start), tz=UTC")
a("        ).isoformat()")
a("    if period_end:")
a("        update_data[\"current_period_end\"] = datetime.fromtimestamp(")
a("            int(period_end), tz=UTC")
a("        ).isoformat()")
a("")
a("    # Find by stripe_subscription_id and update")
a("    db.table(\"subscriptions\").update(update_data).eq(")
a("        \"stripe_subscription_id\", sub.get(\"id\")")
a("    ).execute()")
a("")
a("")
a("async def handle_subscription_deleted(sub: dict[str, Any], db: SupabaseDB) -> None:")
a("    \"\"\"Handle subscription cancellation/deletion.\"\"\"")
a("    db.table(\"subscriptions\").update(")
a("        {")
a("            \"status\": \"canceled\",")
a("            \"updated_at\": datetime.now(UTC).isoformat(),")
a("        }")
a("    ).eq(\"stripe_subscription_id\", sub.get(\"id\")).execute()")
a("")
a("")
a("async def handle_invoice_created(invoice: dict[str, Any], db: SupabaseDB) -> None:")
a("    \"\"\"Handle new invoice creation.\"\"\"")
a("    logger.info(f\"Processing invoice.created: {invoice.get('id')}\")")
a("")
a("    customer_id = invoice.get(\"customer\")")
a("    org_id = None")
a("    if customer_id:")
a("        org_id = await _get_org_by_customer(str(customer_id), db)")
a("    if not org_id:")
a("        logger.warning(")
a("            f\"Cannot link invoice {invoice.get('id')} - no organization found\"")
a("        )")
a("        return")
a("")
a("    subscription_id = invoice.get(\"subscription\")")
a("    sub_id = None")
a("    if subscription_id:")
a("        sub_id = await _get_sub_id(str(subscription_id), db)")
a("")
a("    # Extract amounts with safe defaults")
a("    amount_due_cents = invoice.get(\"amount_due\", 0)")
a("    amount_due = int(amount_due_cents) / 100 if amount_due_cents else 0")
a("    amount_paid_cents = invoice.get(\"amount_paid\", 0)")
a("    amount_paid = int(amount_paid_cents) / 100 if amount_paid_cents else 0")
a("")
a("    # Extract timestamps - use line item periods if invoice period is invalid")
a("    period_start = invoice.get(\"period_start\")")
a("    period_end = invoice.get(\"period_end\")")
a("    due_date = invoice.get(\"due_date\")")
a("")
a("    # If invoice-level periods are invalid, try to get from line items")
a("    if period_start and period_end and period_start >= period_end:")
a("        lines = invoice.get(\"lines\", {}).get(\"data\", [])")
a("        if lines and lines[0].get(\"period\"):")
a("            line_period = lines[0][\"period\"]")
a("            period_start = line_period.get(\"start\")")
a("            period_end = line_period.get(\"end\")")
a("            logger.info(f\"Using line item period for invoice {invoice.get('id')}\")")
a("")
a("    # Skip invoices with invalid periods")
a("    if not period_start or not period_end or period_start >= period_end:")
a("        logger.warning(f\"Skipping invoice {invoice.get('id')} - invalid billing period\")")
a("        return")
a("")
a("    invoice_data = {")
a("        \"organization_id\": org_id,")
a("        \"subscription_id\": sub_id,")
a("        \"stripe_invoice_id\": invoice.get(\"id\"),")
a("        \"amount_due\": amount_due,")
a("        \"amount_paid\": amount_paid,")
a("        \"currency\": invoice.get(\"currency\", \"usd\"),")
a("        \"status\": invoice.get(\"status\", \"draft\"),")
a("        \"period_start\": datetime.fromtimestamp(int(period_start), tz=UTC).isoformat(),")
a("        \"period_end\": datetime.fromtimestamp(int(period_end), tz=UTC).isoformat(),")
a("        \"due_date\": (")
a("            datetime.fromtimestamp(int(due_date), tz=UTC).isoformat()")
a("            if due_date")
a("            else None")
a("        ),")
a("        \"pdf_url\": invoice.get(\"invoice_pdf\"),")
a("        \"updated_at\": datetime.now(UTC).isoformat(),")
a("    }")
a("")
a("    # Check if invoice already exists")
a("    existing = (")
a("        db.table(\"invoices\")")
a("        .select(\"id\")")
a("        .eq(\"stripe_invoice_id\", invoice.get(\"id\"))")
a("        .execute()")
a("    )")
a("")
a("    if existing.data:")
a("        # Update existing invoice")
a("        db.table(\"invoices\").update(invoice_data).eq(")
a("            \"stripe_invoice_id\", invoice.get(\"id\")")
a("        ).execute()")
a("        logger.info(f\"Updated existing invoice: {invoice.get('id')}\")")
a("    else:")
a("        # Insert new invoice")
a("        db.table(\"invoices\").insert(invoice_data).execute()")
a("        logger.info(f\"Created new invoice: {invoice.get('id')}\")")
a("")
a("    logger.info(f\"Invoice created successfully: {invoice.get('id')}\")")
a("")
a("")
a("async def handle_invoice_paid(invoice: dict[str, Any], db: SupabaseDB) -> None:")
a("    \"\"\"Handle successful invoice payment.\"\"\"")
a("    logger.info(f\"Processing invoice.paid: {invoice.get('id')}\")")
a("")
a("    amount_paid_cents = invoice.get(\"amount_paid\", 0)")
a("    amount_paid = int(amount_paid_cents) / 100 if amount_paid_cents else 0")
a("")
a("    # Check if this is a bounty invoice by looking at metadata")
a("    metadata = invoice.get(\"metadata\", {})")
a("    audit_request_id = metadata.get(\"audit_request_id\")")
a("")
a("    if audit_request_id:")
a("        # This is a bounty invoice - handle it specially")
a("        await _handle_bounty_invoice_paid(invoice, audit_request_id, amount_paid, db)")
a("        return")
a("")
a("    # Check if invoice exists first - if not, create it")
a("    existing = (")
a("        db.table(\"invoices\")")
a("        .select(\"id\")")
a("        .eq(\"stripe_invoice_id\", invoice.get(\"id\"))")
a("        .execute()")
a("    )")
a("")
a("    if not existing.data:")
a("        # Invoice does not exist yet, create it first")
a("        logger.info(f\"Invoice {invoice.get('id')} does not exist, creating it first\")")
a("        await handle_invoice_created(invoice, db)")
a("")
a("    # Update payment status")
a("    db.table(\"invoices\").update(")
a("        {")
a("            \"status\": \"paid\",")
a("            \"amount_paid\": amount_paid,")
a("            \"paid_at\": datetime.now(UTC).isoformat(),")
a("            \"pdf_url\": invoice.get(\"invoice_pdf\"),")
a("            \"updated_at\": datetime.now(UTC).isoformat(),")
a("        }")
a("    ).eq(\"stripe_invoice_id\", invoice.get(\"id\")).execute()")
a("")
a("    logger.info(f\"Invoice marked as paid: {invoice.get('id')}\")")
a("")
a("")
a("async def _handle_bounty_invoice_paid(")
a("    invoice: dict[str, Any],")
a("    audit_request_id: str,")
a("    amount_paid: float,")
a("    db: SupabaseDB,")
a(") -> None:")
a("    \"\"\"Handle bounty invoice payment - update audit request to paid status.\"\"\"")
a("    stripe_invoice_id = invoice.get(\"id\")")
a("    logger.info(")
a("        f\"Processing bounty invoice payment: {stripe_invoice_id} \"")
a("        f\"for audit request {audit_request_id}\"")
a("    )")
a("")
a("    # Find our invoice record by stripe_invoice_id")
a("    result = (")
a("        db.table(\"invoices\")")
a("        .select(\"id, audit_request_id\")")
a("        .eq(\"stripe_invoice_id\", stripe_invoice_id)")
a("        .execute()")
a("    )")
a("")
a("    if not result.data:")
a("        logger.warning(f\"Bounty invoice not found in DB: {stripe_invoice_id}\")")
a("        return")
a("")
a("    invoice_data = cast(dict[str, Any], result.data[0])")
a("    now = datetime.now(UTC).isoformat()")
a("")
a("    # Update invoice status")
a("    db.table(\"invoices\").update(")
a("        {")
a("            \"status\": \"paid\",")
a("            \"amount_paid\": amount_paid,")
a("            \"paid_at\": now,")
a("            \"pdf_url\": invoice.get(\"invoice_pdf\"),")
a("            \"updated_at\": now,")
a("        }")
a("    ).eq(\"stripe_invoice_id\", stripe_invoice_id).execute()")
a("")
a("    # Update audit request to paid")
a("    db_audit_request_id = invoice_data.get(\"audit_request_id\") or audit_request_id")
a("    if db_audit_request_id:")
a("        db.table(\"audit_requests\").update(")
a("            {")
a("                \"status\": \"paid\",")
a("                \"updated_at\": now,")
a("            }")
a("        ).eq(\"id\", db_audit_request_id).execute()")
a("")
a("        logger.info(")
a("            f\"Bounty paid for audit request {db_audit_request_id}: \${amount_paid}\"")
a("        )")
a("")
a("")
a("async def handle_invoice_payment_failed(")
a("    invoice: dict[str, Any], db: SupabaseDB")
a(") -> None:")
a("    \"\"\"Handle failed invoice payment.\"\"\"")
a("    logger.info(f\"Processing invoice.payment_failed: {invoice.get('id')}\")")
a("")
a("    # Update invoice status")
a("    db.table(\"invoices\").update(")
a("        {")
a("            \"status\": \"open\",  # Remains open/unpaid")
a("            \"updated_at\": datetime.now(UTC).isoformat(),")
a("        }")
a("    ).eq(\"stripe_invoice_id\", invoice.get(\"id\")).execute()")
a("")
a("    # Update subscription to past_due")
a("    subscription_id = invoice.get(\"subscription\")")
a("    if subscription_id:")
a("        db.table(\"subscriptions\").update(")
a("            {")
a("                \"status\": \"past_due\",")
a("                \"updated_at\": datetime.now(UTC).isoformat(),")
a("            }")
a("        ).eq(\"stripe_subscription_id\", subscription_id).execute()")
a("        logger.info(f\"Subscription marked as past_due: {subscription_id}\")")
a("")
a("    logger.warning(f\"Invoice payment failed: {invoice.get('id')}\")")
a("")
a("")
a("# Helper functions")
a("")
a("")
a("async def _get_org_by_customer(customer_id: str, db: SupabaseDB) -> str | None:")
a("    \"\"\"Get organization ID by Stripe customer ID.\"\"\"")
a("    result = (")
a("        db.table(\"subscriptions\")")
a("        .select(\"organization_id\")")
a("        .eq(\"stripe_customer_id\", customer_id)")
a("        .limit(1)")
a("        .execute()")
a("    )")
a("")
a("    if not result.data:")
a("        return None")
a("    data = cast(list[dict[str, Any]], result.data)")
a("    org_id = data[0].get(\"organization_id\") if data else None")
a("    return str(org_id) if org_id else None")
a("")
a("")
a("async def _get_sub_id(stripe_sub_id: str, db: SupabaseDB) -> str | None:")
a("    \"\"\"Get local subscription UUID by Stripe subscription ID.\"\"\"")
a("    result = (")
a("        db.table(\"subscriptions\")")
a("        .select(\"id\")")
a("        .eq(\"stripe_subscription_id\", stripe_sub_id)")
a("        .limit(1)")
a("        .execute()")
a("    )")
a("")
a("    if not result.data:")
a("        return None")
a("    data = cast(list[dict[str, Any]], result.data)")
a("    sub_id = data[0].get(\"id\") if data else None")
a("    return str(sub_id) if sub_id else None")
a("")
a("")
a("def _map_price_to_plan(price_id: str) -> str:")
a("    \"\"\"Map Stripe price ID to plan name.\"\"\"")
a("    settings = get_stripe_settings()")
a("    price_map = {")
a("        settings.stripe_price_id_growth_annual: \"growth_v2\",")
a("        settings.stripe_price_id_reconcile_annual: \"growth_v2\",")
a("        settings.stripe_price_id_control_annual: \"growth_v2\",")
a("        settings.stripe_price_id_defend_annual: \"growth_v2\",")
a("    }")
a("    return price_map.get(price_id, \"growth_v2\")")
a("")
a("")
a("def _map_subscription_status(status: Any) -> str:")
a("    \"\"\"Map Stripe subscription status to our status enum.\"\"\"")
a("    status_map = {")
a("        \"trialing\": \"trialing\",")
a("        \"active\": \"active\",")
a("        \"past_due\": \"past_due\",")
a("        \"canceled\": \"canceled\",")
a("        \"unpaid\": \"past_due\",")
a("        \"paused\": \"paused\",")
a("    }")
a("    return status_map.get(str(status) if status else \"\", \"active\")")
a("")
a("")
a("async def _claim_webhook_event(db: SupabaseDB, event_id: str, event_type: str) -> bool:")
a("    \"\"\"Atomically claim a webhook event. Returns True if claimed, False if already seen.\"\"\"")
a("    result = (")
a("        db.table(\"stripe_webhook_events\")")
a("        .upsert(")
a("            {")
a("                \"stripe_event_id\": event_id,")
a("                \"event_type\": event_type,")
a("                \"status\": \"processing\",")
a("                \"created_at\": datetime.now(UTC).isoformat(),")
a("            },")
a("            ignore_duplicates=True,")
a("        )")
a("        .execute()")
a("    )")
a("    return bool(result.data)")
a("")
a("")
a("async def _complete_webhook_event(db: SupabaseDB, event_id: str) -> None:")
a("    \"\"\"Mark a claimed event as successfully processed.\"\"\"")
a("    db.table(\"stripe_webhook_events\").update(")
a("        {\"status\": \"succeeded\", \"processed_at\": datetime.now(UTC).isoformat()}")
a("    ).eq(\"stripe_event_id\", event_id).execute()")
a("")
a("")
a("async def _release_webhook_event(db: SupabaseDB, event_id: str) -> None:")
a("    \"\"\"Release a claimed event on failure so Stripe can retry it.\"\"\"")
a("    db.table(\"stripe_webhook_events\").delete().eq(")
a("        \"stripe_event_id\", event_id")
a("    ).execute()")
a("")
a("")
a("# Allowed domains for this webhook handler")
a("CAPVERI_DOMAINS = {\"capveri.com\"}")
a("")
a("def _is_capveri_recipient(to_field: Any) -> bool:")
a("    \"\"\"Check if any recipient is a CapVeri domain.\"\"\"")
