/**
 * Organization domain types for multi-tenant isolation.
 *
 * These Zod schemas match exactly with backend/app/models/organization.py.
 * Values and constraints must be kept in sync.
 */

import { z } from 'zod'

/**
 * Subscription status of an organization.
 */
export const SubscriptionStatus = {
  ACTIVE: 'active',
  TRIAL: 'trial',
  SUSPENDED: 'suspended',
  CANCELLED: 'cancelled',
} as const
export type SubscriptionStatus =
  (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus]

export const SubscriptionStatusSchema = z.enum([
  'active',
  'trial',
  'suspended',
  'cancelled',
])

/**
 * Flexible settings stored as JSONB.
 *
 * These settings allow per-organization customization without
 * requiring schema changes.
 */
export const OrganizationSettingsSchema = z.object({
  timezone: z.string().default('America/New_York'),
  default_currency: z.string().default('USD'),
  fiscal_year_end_month: z.number().int().min(1).max(12).default(12),
})

export type OrganizationSettings = z.infer<typeof OrganizationSettingsSchema>

/**
 * Full organization model from database.
 *
 * Includes all fields: base fields plus database-generated fields.
 */
export const OrganizationSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(255),
  subscription_status: SubscriptionStatusSchema,
  settings: OrganizationSettingsSchema,
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
})

export type Organization = z.infer<typeof OrganizationSchema>

/**
 * DTO for creating an organization.
 *
 * ID and timestamps are generated by the database.
 */
export const OrganizationCreateSchema = z.object({
  name: z.string().min(1).max(255),
  subscription_status: SubscriptionStatusSchema.optional().default('trial'),
  settings: OrganizationSettingsSchema.optional(),
})

export type OrganizationCreate = z.infer<typeof OrganizationCreateSchema>

/**
 * DTO for updating an organization (all fields optional).
 *
 * Only provided fields will be updated; others remain unchanged.
 */
export const OrganizationUpdateSchema = z.object({
  name: z.string().min(1).max(255).optional(),
  subscription_status: SubscriptionStatusSchema.optional(),
  settings: OrganizationSettingsSchema.optional(),
})

export type OrganizationUpdate = z.infer<typeof OrganizationUpdateSchema>
