"""AUTO-GENERATED by generate-videos.mjs - edit marketing/data/videos.json."""

from __future__ import annotations

from typing import TypedDict


class Video(TypedDict):
    slug: str
    youtube_id: str
    title: str
    short_label: str
    description: str
    stage: str
    duration_seconds: int
    upload_date: str
    thumbnail_url: str
    placements: list[str]


VIDEOS_LAST_UPDATED: str = "2026-06-09"
CHANNEL_URL: str = "https://www.youtube.com/@capveri"

VIDEOS: list[Video] = [
    {
        "slug": "forty-percent-material-error",
        "youtube_id": "4015LE26Wsc",
        "title": "40% of CAM Reconciliations Have a Material Error. Find Yours.",
        "short_label": "Most CAM bills hide an error",
        "description": (
            "Many CAM bills have a costly mistake. See where yours could be wrong."
        ),
        "stage": "awareness",
        "duration_seconds": 220,
        "upload_date": "2026-06-02",
        "thumbnail_url": "https://i.ytimg.com/vi/4015LE26Wsc/hqdefault.jpg",
        "placements": [
            "home",
            "cam-reconciliation-software",
            "audit-results-email",
            "videos-library",
        ],
    },
    {
        "slug": "cam-reconciliation-validate",
        "youtube_id": "odNNkE1SfLs",
        "title": "CAM Reconciliation: Catch the Error Before Your Tenant Does",
        "short_label": "Catch CAM errors first",
        "description": (
            "Check your CAM bill before you send it. Find the mistake before your tenant does."  # noqa: E501
        ),
        "stage": "awareness",
        "duration_seconds": 245,
        "upload_date": "2026-06-02",
        "thumbnail_url": "https://i.ytimg.com/vi/odNNkE1SfLs/hqdefault.jpg",
        "placements": [
            "cam-reconciliation-guide",
            "app-reconciliations-empty",
            "videos-library",
        ],
    },
    {
        "slug": "common-area-maintenance-recoverable",
        "youtube_id": "koc5gDxYGw0",
        "title": "Common Area Maintenance: What's Recoverable and What Isn't",
        "short_label": "What CAM costs you can bill",
        "description": (
            "Learn which shared costs tenants pay for. Learn which ones you cannot bill."  # noqa: E501
        ),
        "stage": "educational",
        "duration_seconds": 225,
        "upload_date": "2026-06-02",
        "thumbnail_url": "https://i.ytimg.com/vi/koc5gDxYGw0/hqdefault.jpg",
        "placements": [
            "cam-reconciliation-guide",
            "trial-started-email",
            "content-download-email",
            "app-help",
            "videos-library",
        ],
    },
    {
        "slug": "software-vs-spreadsheets",
        "youtube_id": "PhquEnLt0A0",
        "title": "CAM Reconciliation Software vs Spreadsheets: When to Switch",
        "short_label": "Spreadsheets or software?",
        "description": "See when a spreadsheet is no longer enough for CAM.",
        "stage": "consideration",
        "duration_seconds": 243,
        "upload_date": "2026-06-02",
        "thumbnail_url": "https://i.ytimg.com/vi/PhquEnLt0A0/hqdefault.jpg",
        "placements": [
            "vs-spreadsheets",
            "team-welcome-email",
            "videos-library",
        ],
    },
    {
        "slug": "no-api-no-it-project",
        "youtube_id": "afWoFSIGWk4",
        "title": "CAM Reconciliation Software With No API: Skip the $25K IT Project",
        "short_label": "No IT project needed",
        "description": (
            "Skip the costly setup. Check your CAM from a file you already export."
        ),
        "stage": "objection",
        "duration_seconds": 213,
        "upload_date": "2026-06-02",
        "thumbnail_url": "https://i.ytimg.com/vi/afWoFSIGWk4/hqdefault.jpg",
        "placements": [
            "integrations",
            "videos-library",
        ],
    },
    {
        "slug": "walkthrough-yardi-csv",
        "youtube_id": "kCMogQ3ZJck",
        "title": "CAM Reconciliation Demo: Upload a Yardi CSV and Catch the Errors",
        "short_label": "Watch a quick demo",
        "description": "Watch us upload a Yardi file and find CAM errors fast.",
        "stage": "demo",
        "duration_seconds": 212,
        "upload_date": "2026-06-02",
        "thumbnail_url": "https://i.ytimg.com/vi/kCMogQ3ZJck/hqdefault.jpg",
        "placements": [
            "home",
            "product-tour",
            "sample-report",
            "app-first-import",
            "app-onboarding-welcome",
            "welcome-email",
            "videos-library",
        ],
    },
]

_VIDEOS_BY_SLUG: dict[str, Video] = {video["slug"]: video for video in VIDEOS}


def get_video(slug: str) -> Video | None:
    """Return the video for a slug, or None if not found."""
    return _VIDEOS_BY_SLUG.get(slug)


def get_videos_for_placement(placement: str) -> list[Video]:
    """Return all videos that declare the given placement key."""
    return [video for video in VIDEOS if placement in video["placements"]]


def get_video_for_placement(placement: str) -> Video | None:
    """Return the first video that declares the given placement key."""
    for video in VIDEOS:
        if placement in video["placements"]:
            return video
    return None


def get_watch_url(slug: str) -> str | None:
    """Return the public youtube.com watch URL for a video."""
    video = _VIDEOS_BY_SLUG.get(slug)
    if video is None:
        return None
    return f"https://www.youtube.com/watch?v={video['youtube_id']}"


def get_thumbnail_url(slug: str) -> str | None:
    """Return the stored thumbnail URL for a video."""
    video = _VIDEOS_BY_SLUG.get(slug)
    if video is None:
        return None
    return video["thumbnail_url"]
