import { describe, expect, it } from "vitest";

import {
  calculateReconciliationSnapshots,
  type CalculationDataset,
  type CalculationJobRecord,
  type CalculationLeaseRecord,
  type SnapshotDraft,
} from "../domain/reconciliation/calculator";
import { cumulativeEffectiveMaxMoney } from "../domain/reconciliation/cumulative-cap";
import { Money } from "../domain/reconciliation/money";

/**
 * Penny-exact parity tests for the cumulative / cumulative_compounding cap port.
 *
 * GOLDEN values were generated by running the authoritative Python oracle
 * (backend/app/services/calculation/caps.py apply_cap) directly:
 *
 *   cum_under  (cur 114000, base 100000, 5%, priors [102000,108000]) => 114000.00 (under)
 *   cum_over   (cur 120000, ...                                    ) => 115000.00
 *   cum_bank   (cur 200000, base 100000, 5%, priors [100000,100000]) => 115000.00
 *   cum_y1     (cur 999999, base 100000, 5%, priors [])             => 105000.00
 *   cum_fixed  (cur 200000, base 100000, $5000, priors [103000,106000]) => 115000.00
 *   cum_zerobase (cur 50000, base 0, 5%, priors [])                 => 0.00
 *   cum_rate_gt1 / cum_rate_neg                                      => ValueError
 *
 *   comp_under (cur 114000, base 100000, 5%, priors [102000,108000]) => 114000.00 (under)
 *   comp_over  (cur 130000, ...                                    ) => 121012.50
 *   comp_y1    (cur 999999, base 100000, 5%, priors [])             => 105000.00
 *   comp_bank  (cur 200000, base 100000, 5%, priors [100000,100000]) => 131012.50
 *   comp_fixed (cur 200000, base 100000, $5000, priors [103000,106000]) => 121000.00
 *   comp_rate_gt1 / comp_rate_neg                                    => ValueError
 *
 * The effective-max function returns the cap ceiling; the engine applies
 * current.min(effectiveMax). Every "over"/"bank"/"y1"/"zerobase"/"fixed" golden
 * equals min(current, effectiveMax) where the cap binds, so it equals the
 * effective max directly. The two "under" cases assert the ceiling exceeds the
 * (passing) current amount.
 */

const cap = (overrides: {
  base: string;
  capRate?: string | null;
  capFixedAmount?: string | null;
  priors: string[];
  capType: string;
}): Money =>
  cumulativeEffectiveMaxMoney({
    base: overrides.base,
    capRate: overrides.capRate ?? null,
    capFixedAmount: overrides.capFixedAmount ?? null,
    yearsSinceBase: overrides.priors.length + 1,
    orderedPriorActuals: overrides.priors,
    capType: overrides.capType,
  });

describe("cumulativeEffectiveMaxMoney — cumulative (linear) parity", () => {
  it("3-year under-cap: ceiling exceeds the current amount (golden cum_under)", () => {
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: ["102000", "108000"],
      capType: "cumulative",
    });
    // reference 108000 + annual 5000 + bank 2000 = 115000.00 > current 114000.
    expect(max.toString()).toBe("115000.00");
    expect(Money.parse("114000").min(max).toString()).toBe("114000.00");
  });

  it("3-year over-cap caps to 115000.00 (golden cum_over)", () => {
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: ["102000", "108000"],
      capType: "cumulative",
    });
    expect(Money.parse("120000").min(max).toString()).toBe("115000.00");
  });

  it("bank-then-over consumes the running bank to 115000.00 (golden cum_bank)", () => {
    // priors flat at 100000 bank 5k+10k; reference 100000 + 5000 + 10000 = 115000.
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: ["100000", "100000"],
      capType: "cumulative",
    });
    expect(Money.parse("200000").min(max).toString()).toBe("115000.00");
  });

  it("year 1 with no priors uses base + annual only (golden cum_y1)", () => {
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: [],
      capType: "cumulative",
    });
    expect(max.toString()).toBe("105000.00");
  });

  it("fixed-amount linear caps to 115000.00 (golden cum_fixed)", () => {
    const max = cap({
      base: "100000",
      capFixedAmount: "5000",
      priors: ["103000", "106000"],
      capType: "cumulative",
    });
    // reference 106000 + annual 5000 + bank 4000 = 115000.00.
    expect(Money.parse("200000").min(max).toString()).toBe("115000.00");
  });

  it("zero base with no priors caps to 0.00 (golden cum_zerobase)", () => {
    const max = cap({
      base: "0",
      capRate: "0.05",
      priors: [],
      capType: "cumulative",
    });
    expect(Money.parse("50000").min(max).toString()).toBe("0.00");
  });

  it("cap_rate > 1.0 raises (CAP-5)", () => {
    expect(() =>
      cap({ base: "100000", capRate: "5", priors: [], capType: "cumulative" }),
    ).toThrow(/exceeds maximum/);
  });

  it("negative cap_rate raises (FC-6)", () => {
    expect(() =>
      cap({
        base: "100000",
        capRate: "-0.05",
        priors: [],
        capType: "cumulative",
      }),
    ).toThrow(/non-negative/);
  });
});

describe("cumulativeEffectiveMaxMoney — cumulative_compounding parity", () => {
  it("3-year under-cap: ceiling exceeds the current amount (golden comp_under)", () => {
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: ["102000", "108000"],
      capType: "cumulative_compounding",
    });
    expect(Money.parse("114000").min(max).toString()).toBe("114000.00");
  });

  it("3-year over-cap caps to 121012.50 (golden comp_over)", () => {
    // 100000 * 1.05^3 = 115762.50; bank = (105000+110250) - (102000+108000) = 5250.
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: ["102000", "108000"],
      capType: "cumulative_compounding",
    });
    expect(Money.parse("130000").min(max).toString()).toBe("121012.50");
  });

  it("year 1 with no priors uses base * (1+rate) (golden comp_y1)", () => {
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: [],
      capType: "cumulative_compounding",
    });
    expect(max.toString()).toBe("105000.00");
  });

  it("bank-then-over: once-floored bank yields 131012.50 (golden comp_bank)", () => {
    // This is the case that diverges from cap-bank-ledger's per-year floor.
    // bank = (105000+110250) - (100000+100000) = 15250; max = 115762.50 + 15250.
    const max = cap({
      base: "100000",
      capRate: "0.05",
      priors: ["100000", "100000"],
      capType: "cumulative_compounding",
    });
    expect(Money.parse("200000").min(max).toString()).toBe("131012.50");
  });

  it("fixed-amount compounding (linear) caps to 121000.00 (golden comp_fixed)", () => {
    // max = 100000 + 5000*3 = 115000; bank = (105000+110000)-(103000+106000)=6000.
    const max = cap({
      base: "100000",
      capFixedAmount: "5000",
      priors: ["103000", "106000"],
      capType: "cumulative_compounding",
    });
    expect(Money.parse("200000").min(max).toString()).toBe("121000.00");
  });

  it("cap_rate > 1.0 raises (CAP-5)", () => {
    expect(() =>
      cap({
        base: "100000",
        capRate: "5",
        priors: [],
        capType: "cumulative_compounding",
      }),
    ).toThrow(/exceeds maximum/);
  });

  it("negative cap_rate raises (FC-6)", () => {
    expect(() =>
      cap({
        base: "100000",
        capRate: "-0.05",
        priors: [],
        capType: "cumulative_compounding",
      }),
    ).toThrow(/non-negative/);
  });
});

// ---------------------------------------------------------------------------
// applyCap-level integration: prove the wiring routes cumulative caps through
// the new bank-aware path (NOT the old flat base*(1+rate) formula).
// ---------------------------------------------------------------------------

const ORG_ID = "11111111-1111-4111-8111-111111111111";
const JOB_ID = "22222222-2222-4222-8222-222222222222";
const PROPERTY_ID = "33333333-3333-4333-8333-333333333333";
const LEASE_ID = "44444444-4444-4444-8444-444444444444";
const POOL_ID = "55555555-5555-4555-8555-555555555555";
const ENTRY_ID = "66666666-6666-4666-8666-666666666666";
const PERIOD_START = "2024-01-01";
const PERIOD_END = "2024-12-31";

function onlySnapshot(snapshots: SnapshotDraft[]): SnapshotDraft {
  const snapshot = snapshots[0];
  if (!snapshot || snapshots.length !== 1) {
    throw new Error(`expected exactly one snapshot, got ${snapshots.length}`);
  }
  return snapshot;
}

function job(): CalculationJobRecord {
  return {
    id: JOB_ID,
    organizationId: ORG_ID,
    propertyId: PROPERTY_ID,
    periodStart: PERIOD_START,
    periodEnd: PERIOD_END,
    status: "pending",
    forceRecalculate: false,
  };
}

function cumulativeDataset(): CalculationDataset {
  const leaseRecord: CalculationLeaseRecord = {
    id: LEASE_ID,
    tenantName: "Acme",
    startDate: PERIOD_START,
    endDate: null,
    tenantSqft: "1000",
    recoveryProfile: {
      // pro_rata 1.0 so tenant_share_before_cap == grossed-up GL (120000).
      pro_rata_share: "1.0",
      admin_fee_percentage: "0",
      cap_type: "none",
      excluded_pools: [],
    },
    termVersionId: null,
    versionProRataShare: null,
    versionAdminFeePercentage: null,
    versionManagementFeePercentage: null,
    versionBaseYear: null,
    versionBaseYearAmount: null,
    versionCapType: "cumulative",
    versionCapRate: "0.05",
    versionExcludedPools: null,
  };

  return {
    job: job(),
    property: {
      id: PROPERTY_ID,
      totalRentableSqft: "10000",
      targetOccupancy: null,
    },
    leases: [leaseRecord],
    glEntries: [
      {
        id: ENTRY_ID,
        accountCode: "6100",
        amount: "120000.00",
        transactionDate: "2024-06-30",
        accrualDate: null,
      },
    ],
    expensePools: [
      {
        id: POOL_ID,
        name: "CAM",
        poolType: "operating",
        isGrossUpApplicable: false,
        grossUpTarget: null,
      },
    ],
    poolMappings: [
      {
        expensePoolId: POOL_ID,
        glAccountPattern: "6*",
        allocationPercentage: "1",
        priority: 10,
      },
    ],
    capHistories: [
      {
        leaseId: LEASE_ID,
        priorYearAmount: "108000",
        capBaseYearAmount: "100000",
        priorAmounts: ["102000", "108000"],
      },
    ],
  };
}

describe("calculateReconciliationSnapshots — cumulative cap wiring", () => {
  it("caps to the bank-aware ceiling 115000.00, not the flat base*1.05", async () => {
    // before-cap = 120000. New (correct) ceiling = reference 108000 + annual 5000
    // + bank 2000 = 115000.00. The OLD flat formula would have produced
    // base 100000 * 1.05 = 105000.00 — so 115000.00 proves the new path runs.
    const snapshot = onlySnapshot(
      await calculateReconciliationSnapshots(cumulativeDataset()),
    );
    expect(snapshot.tenant_share_before_cap).toBe("120000.00");
    expect(snapshot.tenant_share_after_cap).toBe("115000.00");
  });
});
