import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(repoRoot, "marketing", "data", "videos.json");

const raw = fs.readFileSync(sourcePath, "utf8");
const data = JSON.parse(raw);

const { lastUpdated, channelUrl, videos } = data;

const REQUIRED_FIELDS = [
  "slug",
  "youtubeId",
  "title",
  "shortLabel",
  "description",
  "stage",
  "durationSeconds",
  "uploadDate",
  "thumbnailUrl",
  "placements",
];

const slugs = new Set();
const youtubeIds = new Set();
for (const video of videos) {
  for (const field of REQUIRED_FIELDS) {
    if (!(field in video) || video[field] === undefined) {
      throw new Error(`Video "${video.slug ?? "?"}" is missing field "${field}"`);
    }
  }
  if (slugs.has(video.slug)) {
    throw new Error(`Duplicate video slug "${video.slug}"`);
  }
  if (youtubeIds.has(video.youtubeId)) {
    throw new Error(`Duplicate youtubeId "${video.youtubeId}"`);
  }
  if (!/^[A-Za-z0-9_-]{11}$/.test(video.youtubeId)) {
    throw new Error(`Invalid youtubeId "${video.youtubeId}" for "${video.slug}"`);
  }
  if (typeof video.durationSeconds !== "number" || video.durationSeconds <= 0) {
    throw new Error(`Invalid durationSeconds for "${video.slug}"`);
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(video.uploadDate)) {
    throw new Error(`Invalid uploadDate "${video.uploadDate}" for "${video.slug}"`);
  }
  // Newlines in string fields would break the single-line Python/TS emission.
  for (const field of ["title", "shortLabel", "description", "stage"]) {
    if (/[\r\n]/.test(String(video[field]))) {
      throw new Error(`Field "${field}" for "${video.slug}" must not contain newlines`);
    }
  }
  slugs.add(video.slug);
  youtubeIds.add(video.youtubeId);
}

const slugUnion = videos.map((v) => `"${v.slug}"`).join(" | ");

const tsContent = `/* AUTO-GENERATED by scripts/generate-videos.mjs - edit marketing/data/videos.json instead */

export type VideoSlug = ${slugUnion};

export interface Video {
  slug: VideoSlug;
  youtubeId: string;
  title: string;
  shortLabel: string;
  description: string;
  stage: string;
  durationSeconds: number;
  uploadDate: string;
  thumbnailUrl: string;
  placements: string[];
}

export const VIDEOS_LAST_UPDATED = ${JSON.stringify(lastUpdated)};
export const CHANNEL_URL = ${JSON.stringify(channelUrl)};

export const VIDEOS: Video[] = ${JSON.stringify(videos, null, 2)};

const VIDEOS_BY_SLUG: Record<string, Video> = Object.fromEntries(
  VIDEOS.map((video) => [video.slug, video]),
);

/** Returns the video for a slug, or undefined if not found. */
export function getVideo(slug: string): Video | undefined {
  return VIDEOS_BY_SLUG[slug];
}

/** Returns all videos that declare the given placement key. */
export function getVideosForPlacement(placement: string): Video[] {
  return VIDEOS.filter((video) => video.placements.includes(placement));
}

/** Returns the first video that declares the given placement key. */
export function getVideoForPlacement(placement: string): Video | undefined {
  return VIDEOS.find((video) => video.placements.includes(placement));
}

/** Returns the privacy-friendly youtube-nocookie.com embed URL for a video. */
export function getEmbedUrl(slug: string): string | undefined {
  const video = VIDEOS_BY_SLUG[slug];
  if (!video) return undefined;
  return \`https://www.youtube-nocookie.com/embed/\${video.youtubeId}\`;
}

/** Returns the public youtube.com watch URL for a video. */
export function getWatchUrl(slug: string): string | undefined {
  const video = VIDEOS_BY_SLUG[slug];
  if (!video) return undefined;
  return \`https://www.youtube.com/watch?v=\${video.youtubeId}\`;
}
`;

const esc = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');

// Mirrors the pyStr helper in generate-plan-tiers.mjs: keep generated Python
// within the 88-char line limit, wrapping long values and adding a noqa only
// when the wrapped value line itself still exceeds the limit.
const pyStr = (indent, key, value) => {
  const escaped = esc(value);
  const singleLine = `${indent}"${key}": "${escaped}",`;
  if (singleLine.length <= 88) return singleLine;
  const innerIndent = indent + "    ";
  const innerLine = `${innerIndent}"${escaped}"`;
  const noqa = innerLine.length > 88 ? "  # noqa: E501" : "";
  return `${indent}"${key}": (\n${innerLine}${noqa}\n${indent}),`;
};

const pyVideos = videos
  .map((v) => {
    const placements = v.placements.map((p) => `            "${p}",`).join("\n");
    return [
      "    {",
      pyStr("        ", "slug", v.slug),
      pyStr("        ", "youtube_id", v.youtubeId),
      pyStr("        ", "title", v.title),
      pyStr("        ", "short_label", v.shortLabel),
      pyStr("        ", "description", v.description),
      pyStr("        ", "stage", v.stage),
      `        "duration_seconds": ${v.durationSeconds},`,
      pyStr("        ", "upload_date", v.uploadDate),
      pyStr("        ", "thumbnail_url", v.thumbnailUrl),
      `        "placements": [\n${placements}\n        ],`,
      "    },",
    ].join("\n");
  })
  .join("\n");

const pyContent = `"""AUTO-GENERATED by generate-videos.mjs - edit marketing/data/videos.json."""

from __future__ import annotations

from typing import TypedDict


class Video(TypedDict):
    slug: str
    youtube_id: str
    title: str
    short_label: str
    description: str
    stage: str
    duration_seconds: int
    upload_date: str
    thumbnail_url: str
    placements: list[str]


VIDEOS_LAST_UPDATED: str = "${lastUpdated}"
CHANNEL_URL: str = "${channelUrl}"

VIDEOS: list[Video] = [
${pyVideos}
]

_VIDEOS_BY_SLUG: dict[str, Video] = {video["slug"]: video for video in VIDEOS}


def get_video(slug: str) -> Video | None:
    """Return the video for a slug, or None if not found."""
    return _VIDEOS_BY_SLUG.get(slug)


def get_videos_for_placement(placement: str) -> list[Video]:
    """Return all videos that declare the given placement key."""
    return [video for video in VIDEOS if placement in video["placements"]]


def get_video_for_placement(placement: str) -> Video | None:
    """Return the first video that declares the given placement key."""
    for video in VIDEOS:
        if placement in video["placements"]:
            return video
    return None


def get_watch_url(slug: str) -> str | None:
    """Return the public youtube.com watch URL for a video."""
    video = _VIDEOS_BY_SLUG.get(slug)
    if video is None:
        return None
    return f"https://www.youtube.com/watch?v={video['youtube_id']}"


def get_thumbnail_url(slug: str) -> str | None:
    """Return the stored thumbnail URL for a video."""
    video = _VIDEOS_BY_SLUG.get(slug)
    if video is None:
        return None
    return video["thumbnail_url"]
`;

const pyPath = path.join(
  repoRoot,
  "backend",
  "app",
  "services",
  "email",
  "videos.py",
);
fs.writeFileSync(pyPath, pyContent, "utf8");

const tsPath = path.join(repoRoot, "frontend", "src", "generated", "videos.ts");
fs.writeFileSync(tsPath, tsContent, "utf8");

console.log("Generated video artifacts (videos.py + videos.ts).");
