"""AUTO-GENERATED by scripts/generate-plan-tiers.mjs - edit plan-tiers.json instead."""

from __future__ import annotations

from typing import TypedDict


class TierAudience(TypedDict):
    who: str
    portfolio: str
    primary_jobs: list[str]


class UnitPricingBand(TypedDict):
    min_units: int
    max_units: int | None
    price_per_unit_annual: int


class SubscriptionTier(TypedDict):
    id: str
    name: str
    base_annual: int | None
    included_units: int
    price_per_unit_annual: int | None
    unit_pricing_bands: list[UnitPricingBand]
    min_units: int
    max_units: int | None
    popular: bool
    description: str
    tagline: str
    audience: TierAudience
    comparison_label: str
    included_in_trial: bool
    primary_cta_id: str


class LaunchOfferPhase(TypedDict):
    phase_index: int
    code: str
    label: str
    discount_percent: int
    max_redemptions: int


class LaunchOffer(TypedDict):
    checkout_param: str
    code: str
    label: str
    discount_percent: int
    max_redemptions: int
    phases: list[LaunchOfferPhase]


TRIAL_DAYS: int = 30
TRIAL_REMINDER_DAYS: int = 3

LAUNCH_OFFER: LaunchOffer = {
    "checkout_param": "offer",
    "code": "80OFF",
    "label": "80% off the first year",
    "discount_percent": 80,
    "max_redemptions": 300,
    "phases": [
        {
            "phase_index": 1,
            "code": "80OFF",
            "label": "80% off the first year",
            "discount_percent": 80,
            "max_redemptions": 300,
        },
    ],
}

TIERS: list[SubscriptionTier] = [
    {
        "id": "reconcile",
        "name": "Reconcile",
        "base_annual": 4990,
        "included_units": 25,
        "price_per_unit_annual": None,
        "unit_pricing_bands": [
            {
                "min_units": 26,
                "max_units": 150,
                "price_per_unit_annual": 179,
            },
            {
                "min_units": 151,
                "max_units": 500,
                "price_per_unit_annual": 169,
            },
            {
                "min_units": 501,
                "max_units": 2500,
                "price_per_unit_annual": 159,
            },
            {
                "min_units": 2501,
                "max_units": None,
                "price_per_unit_annual": 149,
            },
        ],
        "min_units": 1,
        "max_units": None,
        "popular": False,
        "description": (
            "For commercial landlords who want lease-accurate CAM reconciliation without spreadsheet drift."  # noqa: E501
        ),
        "tagline": "Run lease-accurate CAM reconciliation without spreadsheet drift.",
        "audience": {
            "who": "Commercial landlords and property managers",
            "portfolio": "Starts at $4,990/year for up to 25 rentable units",
            "primary_jobs": [
                "Stop reconciling CAM in Excel",
                "Price the subscription by rentable unit count",
                "Produce tenant-ready exception summaries",
            ],
        },
        "comparison_label": "Annual Reconcile subscription",
        "included_in_trial": True,
        "primary_cta_id": "startTrial",
    },
]

# Features available in the Reconcile tier
RECONCILE_ONLY_FEATURES: set[str] = {
    "gl_import_and_parsing",
    "cam_reconciliation",
    "leakage_detection",
    "expense_pools",
    "lease_management",
    "rent_roll_upload",
    "basic_reporting",
    "csv_exports",
    "unlimited_team_members",
    "portfolio_dashboard",
    "cap_bank_tracking",
    "trend_analysis",
    "anomaly_alerts",
    "pdf_exports",
    "excel_exports",
    "noi_impact_calculator",
    "tax_protest",
    "ai_lease_extraction",
    "ai_gl_narrative_analysis",
    "tenant_portal",
    "dispute_system",
    "sb1103_compliance_export",
    "demand_letters",
    "audit_defense_package",
    "priority_support",
    "support_access",
    "published_unit_pricing",
    "onboarding_support",
}


# Cumulative feature sets (tier includes all lower tiers)
RECONCILE_FEATURES: set[str] = RECONCILE_ONLY_FEATURES

FEATURE_LABELS: dict[str, str] = {
    "gl_import_and_parsing": "GL import and parsing",
    "cam_reconciliation": "CAM reconciliation",
    "leakage_detection": "Exception summary",
    "expense_pools": "Expense pool management",
    "lease_management": "Lease management and versioning",
    "rent_roll_upload": "Rent roll upload",
    "basic_reporting": "Reconciliation summaries",
    "csv_exports": "CSV exports",
    "unlimited_team_members": "Unlimited team members",
    "portfolio_dashboard": "Portfolio dashboard",
    "cap_bank_tracking": "Cumulative cap bank tracking",
    "trend_analysis": "Year-over-year trend analysis",
    "anomaly_alerts": "Anomaly detection alerts",
    "pdf_exports": "PDF reconciliation reports",
    "excel_exports": "Excel exports",
    "noi_impact_calculator": "NOI impact calculator",
    "tax_protest": "HCAD tax protest normalization",
    "ai_lease_extraction": "AI lease extraction with human review",
    "ai_gl_narrative_analysis": "AI GL analysis + CapEx screening",
    "tenant_portal": "Tenant self-serve portal",
    "dispute_system": "Dispute management with audit trail",
    "sb1103_compliance_export": "California SB 1103 compliance export",
    "demand_letters": "Tenant response templates",
    "audit_defense_package": "Audit defense package",
    "priority_support": "Priority support",
    "support_access": "Support access",
    "published_unit_pricing": "Published pricing for every unit count",
    "onboarding_support": "Onboarding support",
}

FEATURE_TIERS: dict[str, str] = {
    "gl_import_and_parsing": "reconcile",
    "cam_reconciliation": "reconcile",
    "leakage_detection": "reconcile",
    "expense_pools": "reconcile",
    "lease_management": "reconcile",
    "rent_roll_upload": "reconcile",
    "basic_reporting": "reconcile",
    "csv_exports": "reconcile",
    "unlimited_team_members": "reconcile",
    "portfolio_dashboard": "reconcile",
    "cap_bank_tracking": "reconcile",
    "trend_analysis": "reconcile",
    "anomaly_alerts": "reconcile",
    "pdf_exports": "reconcile",
    "excel_exports": "reconcile",
    "noi_impact_calculator": "reconcile",
    "tax_protest": "reconcile",
    "ai_lease_extraction": "reconcile",
    "ai_gl_narrative_analysis": "reconcile",
    "tenant_portal": "reconcile",
    "dispute_system": "reconcile",
    "sb1103_compliance_export": "reconcile",
    "demand_letters": "reconcile",
    "audit_defense_package": "reconcile",
    "priority_support": "reconcile",
    "support_access": "reconcile",
    "published_unit_pricing": "reconcile",
    "onboarding_support": "reconcile",
}


def _get_tier(tier_id: str) -> SubscriptionTier | None:
    for tier in TIERS:
        if tier["id"] == tier_id:
            return tier
    return None


def get_annual_price(tier_id: str) -> int | None:
    """Return the flat annual subscription price in dollars for a given tier."""
    tier = _get_tier(tier_id)
    return tier["base_annual"] if tier else None


def get_annual_total_cents(tier_id: str, unit_count: int) -> int | None:
    """Return total annual charge in cents for a tier and rentable unit count."""
    tier = _get_tier(tier_id)
    if not tier:
        return None
    base_annual = tier["base_annual"]
    if base_annual is None:
        return None
    resolved_unit_count = max(unit_count, tier["min_units"])
    unit_pricing_bands = tier["unit_pricing_bands"]
    if unit_pricing_bands:
        overage_total = 0
        for band in unit_pricing_bands:
            if resolved_unit_count < band["min_units"]:
                continue
            band_max = band["max_units"] or resolved_unit_count
            band_unit_count = max(
                min(resolved_unit_count, band_max) - band["min_units"] + 1,
                0,
            )
            overage_total += band_unit_count * band["price_per_unit_annual"]
        return (base_annual + overage_total) * 100
    price_per_unit_annual = tier["price_per_unit_annual"]
    if price_per_unit_annual is None:
        return None
    overage_units = max(resolved_unit_count - tier["included_units"], 0)
    return (base_annual + overage_units * price_per_unit_annual) * 100


def get_launch_offer_annual_cents(tier_id: str, unit_count: int = 1) -> int | None:
    """Return first-year launch offer charge in cents for a tier."""
    annual_total_cents = get_annual_total_cents(tier_id, unit_count)
    if annual_total_cents is None:
        return None
    discounted_cents = annual_total_cents * (100 - LAUNCH_OFFER["discount_percent"])
    return ((discounted_cents + 9999) // 10000) * 100


def get_band_for_count(unit_count: int) -> str:
    """Return tier id for a given rentable unit count."""
    for tier in TIERS:
        max_units = tier["max_units"]
        if max_units is None:
            return tier["id"]
        if unit_count <= max_units:
            return tier["id"]
    return TIERS[-1]["id"]


def get_features_for_tier(tier_id: str) -> set[str]:
    """Return the set of feature keys available for a given tier."""
    _tier_features: dict[str, set[str]] = {
        "reconcile": RECONCILE_FEATURES,
    }
    return _tier_features.get(tier_id, set())


def has_feature(tier_id: str, feature_key: str) -> bool:
    """Check if a specific feature is available in a given tier."""
    return feature_key in get_features_for_tier(tier_id)
